In [5]:
# numpy
import numpy as np

# pip install sympy
import sympy as sp

# matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [11]:

def gaussian_elim(A):
    m, n = A.shape
    A = np.float64(A)
    
    #YOUR CODE HERE
    i = 0 # index of row of A[i,j]
    j = 0 # index of column of A[i,j]

    while (i < m and j < n):
        # Find the index of the A[i,j] with maximum absolute value in each column. 
        max_index_column = A[:, j].tolist().index(max(abs(A[:, j])))

        # Check whether A[i,j] is 0.
        if A[max_index_column,j] != 0:
            # Swap the line with maximum absolute value A[i,j] to A[i].
            A[[i, max_index_column]] = A[[max_index_column, i]]
            # Make sure A[i,j] is 1.
            A[i] = A[i] / A[i, j]
            
            # let other element be 0 in the column j (line i+1 to the last line).
            for u in range(i+1, m):
                A[u] -= A[u,j]*A[i]
            
            # let other element be 0 in the column j (the first line to line i-1).
            for v in range(0, i):
                A[v] = A[j]*A[v,j] - A[v]
                
        i += 1    
        j += 1
        
        p = m if m<n else n
        # make sure each pivot is 1 instead of -1.
        for k in range(0, p-1):
            if A[k,k] == -1:
                A[k] = (-1) * A[k]
    return A

In [12]:
A = np.array([[2, 0, 3, 1, 0, 2],
             [1, 3, 2, 0, 3, 1],
             [3, 2, 3, 1, 1, 2]])
print(gaussian_elim(A))
#The result should look like
# [[ 1.          0.          0.          0.36363636 -0.81818182  0.18181818]
#  [ 0.          1.          0.         -0.18181818  0.90909091 -0.09090909]
#  [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]

[[ 1.         -0.         -0.          0.36363636 -0.81818182  0.18181818]
 [-0.          1.         -0.         -0.18181818  0.90909091 -0.09090909]
 [ 0.          0.          1.          0.09090909  0.54545455  0.54545455]]
